services:
  _defaults:
    autoconfigure: true
    autowire: true

  SchulIT\IdpExchangeBundle\Command\:
    resource: '../../Command'
    tags: [ 'console.command' ]

  SchulIT\IdpExchangeBundle\Command\RunCommand:
    tags:
      - { name: shapecode_cron.cron_job, expression: '*\/5 * * * *' }

  SchulIT\IdpExchangeBundle\Command\EnqueueCommand:
    tags:
      - { name: shapecode_cron.cron_job, expression: '* *\/2 * * *' }