services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SchoolIT\IdpExchangeBundle\Controller\:
    resource: '../../Controller'
    tags:
      - 'controller.service_arguments'