parameters:
  idp_exchange.key_value.table_name: 'idp_exchange'

services:
  _defaults:
    public: false

  SchulIT\IdpExchangeBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    autoconfigure: true

  SchulIT\IdpExchange\Client:
    arguments:
      - '' # Endpoint
      - '' # Token
      - '' # Guzzle
      - '@JMS\Serializer\SerializerInterface' # JMS Serializer
      - '@logger' # Logger

  Webmozart\KeyValueStore\DbalStore:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%idp_exchange.key_value.table_name%'

  SchulIT\IdpExchangeBundle\Service\SynchronizationManager:
    class:
    arguments:
      - '%idp_exchange.user_limit%'
      - '@SchulIT\IdpExchange\Client'
      - '@SchulIT\IdpExchangeBundle\Repository\UpdateUserRepositoryInterface'
      - '@Webmozart\KeyValueStore\DbalStore'
      - ''
      - ''
      - '@logger'

  SchulIT\IdpExchangeBundle\Controller\AdminController:
    arguments:
      - '@SchulIT\IdpExchangeBundle\Service\SynchronizationManager'

