parameters:
  idp_exchange.key_value.table_name: 'idp_exchange'

services:
  _defaults:
    public: false

  SchoolIT\IdpExchangeBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true
    tags: [ 'console.command' ]

  SchoolIT\IdpExchangeBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    autoconfigure: true

  SchoolIT\IdpExchange\Client:
    arguments:
      - '' # Endpoint
      - '' # Token
      - '' # Guzzle
      - '@JMS\Serializer\SerializerInterface' # JMS Serializer
      - '@logger' # Logger

  Webmozart\KeyValueStore\DbalStore:
    arguments:
      - "@doctrine.dbal.default_connection"
      - "%idp_exchange.key_value.table_name%"

  SchoolIT\IdpExchangeBundle\Service\SynchronizationManager:
    class:
    arguments:
      - "%idp_exchange.user_limit%"
      - "@idp_exchange.client"
      - "@SchoolIT\IdpExchangeBundle\Repository\UpdateUserRepositoryInterface"
      - "@Webmozart\KeyValueStore\DbalStore"
      - ""
      - ""
      - "@logger"

  SchoolIT\IdpExchangeBundle\Controller\AdminController:
    arguments:
      - "@SchoolIT\IdpExchangeBundle\Service\SynchronizationManager"

